In [1]:
import pandas as pd

## Data Exploring

In [2]:
#read the excel file
file_path= "../raw/online_retail_II.xlsx"
excel_file = pd.ExcelFile(file_path)
excel_file.sheet_names
df_2009 = pd.read_excel(file_path, sheet_name='Year 2009-2010')
df_2010 = pd.read_excel(file_path, sheet_name='Year 2010-2011')

In [3]:
### How many rows?
print(df_2009.shape)
print(df_2010.shape)

###check if the columns match
df_2009.columns.equals(df_2010.columns)

##Merge the two dataframes into one dataframe
df_retail = pd.concat(
    [df_2009, df_2010],
    ignore_index=True
)

(525461, 8)
(541910, 8)

In [4]:
### What are the columns? data types and total number of rows?
df_retail.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 65.1+ MB

In [5]:
#Change column name 
df_retail.rename(columns={"Customer ID": "CustomerID"}, inplace=True)

In [6]:
df_retail.columns.tolist()

['Invoice',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'Price',
 'CustomerID',
 'Country']

In [7]:
# How many unique invoices?
print(f"Unique invoices: {df_retail['Invoice'].nunique()}")

Unique invoices: 53628

In [8]:
# How many unique products?
print(f"Unique product stockcodes: {df_retail['StockCode'].nunique()}")
print(f"Unique product descriptions: {df_retail['Description'].nunique()}")

Unique product stockcodes: 5305
Unique product descriptions: 5698

In [9]:

# How many unique products?
print(f"Unique product codes: {df_retail['StockCode'].nunique()}")
print(f"Unique product descriptions: {df_retail['Description'].nunique()}")

Unique product codes: 5305
Unique product descriptions: 5698

In [10]:
### How many unique customers?
print(f"Unique customers: {df_retail['CustomerID'].nunique()}")

Unique customers: 5942

In [11]:
df_retail.groupby("CustomerID")["Invoice"].nunique().sort_values(ascending=False).head(10)

CustomerID
14911.0    510
12748.0    365
17841.0    289
15311.0    270
14606.0    259
13089.0    247
14156.0    202
14527.0    190
13694.0    164
14646.0    164
Name: Invoice, dtype: int64

In [12]:
### How much missing data?
missing_values = df_retail.isna().sum()
missing_percentage = df_retail.isna().mean()*100

print(missing_values)
print(missing_percentage)

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
CustomerID     243007
Country             0
dtype: int64
Invoice         0.000000
StockCode       0.000000
Description     0.410541
Quantity        0.000000
InvoiceDate     0.000000
Price           0.000000
CustomerID     22.766873
Country         0.000000
dtype: float64

In [13]:
# Check whether any invoice numbers appear both with and without a Customer ID.
# An empty set means missing Customer IDs cannot be recovered using the invoice number.
invoices_with_missing_customer_id = set(df_retail[df_retail['CustomerID'].isna()]['Invoice'])
invoices_with_customer_id =   set(df_retail[df_retail['CustomerID'].notna()]['Invoice'])
invoices_with_missing_customer_id.intersection(invoices_with_customer_id)

set()

In [14]:
### How many cancellations?
cancelled = df_retail[
    df_retail["Invoice"].astype(str).str.startswith("C")
]
print(f"Number of cancelled invoices: {cancelled.shape[0]}")
print(f"Number of unique cancelled invoice IDs: {cancelled['Invoice'].nunique()}")

Number of cancelled invoices: 19494
Number of unique cancelled invoice IDs: 8292

In [15]:
### What date range do we have?
print(f"Date range: {df_retail['InvoiceDate'].min()} to {df_retail['InvoiceDate'].max()}")

#is every month represented in the data?
df_retail["InvoiceDate"].dt.to_period("M").value_counts().sort_index()
#it is december 2009 to december 2011.

Date range: 2009-12-01 07:45:00 to 2011-12-09 12:50:00

InvoiceDate
2009-12    45228
2010-01    31555
2010-02    29388
2010-03    41511
2010-04    34057
2010-05    35323
2010-06    39983
2010-07    33383
2010-08    33306
2010-09    42091
2010-10    59098
2010-11    78015
2010-12    65004
2011-01    35147
2011-02    27707
2011-03    36748
2011-04    29916
2011-05    37030
2011-06    36874
2011-07    39518
2011-08    35284
2011-09    50226
2011-10    60742
2011-11    84711
2011-12    25526
Freq: M, Name: count, dtype: int64

In [16]:
#duplicated rows

df_retail[df_retail.duplicated()]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID,Country
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067136,581538,22068,BLACK PIRATE TREASURE CHEST,1,2011-12-09 11:34:00,0.39,14446.0,United Kingdom
1067150,581538,23318,BOX OF 6 MINI VINTAGE CRACKERS,1,2011-12-09 11:34:00,2.49,14446.0,United Kingdom
1067153,581538,22992,REVOLVER WOODEN RULER,1,2011-12-09 11:34:00,1.95,14446.0,United Kingdom
1067160,581538,22694,WICKER STAR,1,2011-12-09 11:34:00,2.10,14446.0,United Kingdom
1067162,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,2011-12-09 11:34:00,2.08,14446.0,United Kingdom

## Data Cleaning

In [17]:
#Prepare data for cleaning
df_clean = df_retail.copy()

### 1. Standardize column names

In [18]:
#Change column names lowcase, clean and replace spaces with underscores
df_clean.columns = ( 
    df_clean.columns.str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
print(df_clean.columns.tolist())

['invoice', 'stockcode', 'description', 'quantity', 'invoicedate', 'price', 'customerid', 'country']

In [19]:
### 2. Check/fix data types
df_clean.dtypes
df_clean['invoice'] = df_clean['invoice'].astype(str)
df_clean["customerid"] = df_clean["customerid"].astype("Int64")
df_clean["stockcode"] = df_clean["stockcode"].astype("string")
df_clean["description"] = df_clean["description"].astype("string")

In [36]:
### 3. Investigate duplicates
duplicate_count = df_clean.duplicated().sum()

duplicate_count

np.int64(0)

In [ ]:
df_clean[df_clean.duplicated(keep=False)].head(20)

,invoice,stockcode,description,quantity,invoicedate,price,customerid,country
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329,United Kingdom
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329,United Kingdom
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984,United Kingdom
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984,United Kingdom
656,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984,United Kingdom

In [22]:
df_clean = df_clean.drop_duplicates() 
df_clean.duplicated().sum()

np.int64(0)

### Duplicate handling:
 Exact duplicate transaction rows were found. Since identical records would otherwise double-count quantities and revenue, exact duplicates were removed. As the dataset does not contain a unique line-item identifier, this is treated as a documented cleaning assumption.

### 4. Handle missing Description

In [23]:
df_clean['description'].isna().sum()

np.int64(4275)

In [24]:
missing_description_codes = df_clean[
    df_clean["description"].isna()
]["stockcode"].unique()

In [25]:
code = missing_description_codes[0]

df_clean[df_clean["stockcode"] == code][
    ["stockcode", "description"]
].drop_duplicates()

    stockcode description
470     21646        <NA>

In [26]:
missing_codes = set(
    df_clean[df_clean["description"].isna()]["stockcode"]
)
known_codes = set(
    df_clean[df_clean["description"].notna()]["stockcode"]
)
recoverable_codes = missing_codes.intersection(known_codes)

len(recoverable_codes)

2096

In [27]:
### investigate the stockcode with the most unique descriptions
df_clean.groupby("stockcode")["description"].nunique().sort_values(
    ascending=False
).head(20)
### to investigate further, drop duplicates and count the number of unique descriptions for stockcode 20713
df_clean[df_clean["stockcode"] == "20713"][
    ["stockcode", "description"]
].drop_duplicates()

### how much description variation is there for stockcode 20713?
df_clean[df_clean["stockcode"] == "20713"]["description"].value_counts()

description
JUMBO BAG OWLS                  1337
missing                            1
wrongly marked. 23343 in box       1
wrongly coded-23343                1
found                              1
Found                              1
wrongly marked 23343               1
Marked as 23343                    1
wrongly coded 23343                1
Name: count, dtype: Int64

In [28]:
### so make a new column to flag internal notes in the description column. Internal notes are descriptions that contain the words "wrongly", "missing", "found", or "marked".
df_clean["is_internal_note"] = (
    df_clean["description"]
    .str.lower()
    .str.contains("wrongly|missing|found|marked", na=False)
)

In [29]:
### To make a RFM analysis we keep not na customerids in a copyied data frame
df_customer = df_clean[
    df_clean["customerid"].notna()
].copy()
df_customer["customerid"].nunique()

5942

### Which transactions should count as a real completed purchase for RFM?
--- Recency (R): How recently a customer made a purchase. Recent buyers are more engaged and likely to buy again.
--- Frequency (F): How often a customer makes purchases within a set period. Higher frequency shows loyalty and habit.
--- Monetary Value (M): How much money a customer spends on purchases overall. This identifies your biggest financial contributors.

That's where we look at Invoice starting with C and negative Quantity.
For RFM, we want completed purchase transactions only. So we’ll create a separate DataFrame and exclude cancelled/invalid sales from that one.

In [30]:
df_rfm = df_customer.copy()
print('Number of cancelled orders:', (df_rfm["invoice"].astype(str).str.startswith("C")).sum())
print('Number of negative quantity items:', (df_rfm["quantity"] <= 0).sum())
print('Number of negative prices:', (df_rfm["price"] < 0).sum())

Number of cancelled orders: 18390
Number of negative quantity items: 18390
Number of negative prices: 0

In [31]:
df_rfm = df_rfm[
    (~df_rfm["invoice"].astype(str).str.startswith("C")) &
    (df_rfm["quantity"] > 0) &
    (df_rfm["price"] > 0)
].copy()

### RFM analysis 1 step is look at frequency

Frequency

How many unique orders did each customer make?

In [44]:
frequency = (
    df_rfm.groupby("customerid")["invoice"]
    .nunique()
    .rename("frequency")
)
frequency.sort_values(ascending=False).head(20)

customerid
14911    398
12748    336
17841    211
15311    208
13089    203
14606    192
14156    156
17850    155
14646    151
18102    145
13694    143
15061    127
14527    122
17949    118
12971    116
13798    110
16422    109
16029    107
13408    106
17961    100
Name: frequency, dtype: int64

### Second step total revenue for each costumer

In [ ]:
# calculate the revenue to see how much each customer spend.
df_rfm['revenue'] = df_rfm['price'] * df_rfm['quantity']

0           83.40
1           81.00
2           81.00
3          100.80
4           30.00
            ...
1067366     12.60
1067367     16.60
1067368     16.60
1067369     14.85
1067370     18.00
Name: revenue, Length: 779425, dtype: float64

In [51]:
#monetary shows customer and revanue in total
monetary = (
    df_rfm.groupby('customerid')['revenue'].sum()
    .rename('monetary')
)

In [52]:
# highesst spending customers
monetary.sort_values(ascending=False).head(10)

customerid
18102    580987.04
14646    528602.52
14156    313437.62
14911    291420.81
17450    244784.25
13694    195640.69
17511    172132.87
16446    168472.50
16684    147142.77
12415    144458.37
Name: monetary, dtype: float64

In [55]:
df_rfm.columns.to_list()

['invoice',
 'stockcode',
 'description',
 'quantity',
 'invoicedate',
 'price',
 'customerid',
 'country',
 'is_internal_note',
 'revenue']

In [59]:
#Calculate Recency
#Find each customer’s latest purchase date, then calculate how many days ago that was relative to the dataset end date.
latest_purchase = df_rfm.groupby("customerid")["invoicedate"].max()
reference_date = df_rfm["invoicedate"].max() + pd.Timedelta(days=1)

In [ ]:
recency = (reference_date - latest_purchase).dt.days
recency = recency.rename("ecency")

In [72]:
#look at our dataset rfm
rfm = pd.concat(
    [recency, frequency, monetary],
    axis=1
)

In [76]:
rfm.head().sort_valuesby(ascending=False)

AttributeError: 'DataFrame' object has no attribute 'sort_valuesby'